library(tidyr)
library(dplyr)
library(ggplot2)
setwd("C:/Users/sissy/Desktop/test Git/ADS2_2019-21/Problem_Sets/6")
gdp <- read.csv("GDP.csv",na.strings = "",header = T,check.names = F)
gdp <- gather(gdp,key = "Year",value = "GDP",factor_key = T,-CountryName,convert = T)
gdp.noNA <- drop_na(gdp)
gdp.sub <- dplyr::filter(gdp.noNA,CountryName %in% c("France","Germany","Italy","Greece"),Year %in% c(1960,1970,1980,1990,2000,2010,2018))
summary(gdp.sub)
g <- ggplot(data = gdp.sub,aes(x=Year,y = GDP,color=CountryName))
g1 <- g+geom_point()+geom_line()+geom_text(aes(label=GDP))+labs(title = "GDP trends in the countries")
g1
g2 <- g1+scale_y_continuous(trans = 'log2')+facet_wrap(~CountryName,ncol = 4)
g2
g+geom_point()+geom_smooth(method = "loess")
g+geom_area(aes(fill=CountryName),position = "fill")
ggplot(data = gdp.sub,aes(x = Year,y = GDP))+geom_bar(stat = "identity",aes(group=CountryName,fill=CountryName),position = "dodge")
gdp.2018 <- dplyr::filter(gdp.sub,Year == "2018")
install.packages("maps")
library(maps)
eu_map <- map_data("world",region = c("France","Germany","Italy","Greece"))
ggplot(eu_map,aes(x=long,y=lat,group=group))+geom_polygon()
ggplot(eu_map,aes(x=long,y=lat,group=group))+geom_polygon(aes(fill=region))
gdp.map <- dplyr::left_join(eu_map,gdp.2018,by=c("region"="CountryName"))
gmap <- ggplot(gdp.map,aes(x=long,y=lat,group=group))+geom_polygon(aes(fill=GDP))+labs(title = "2018 GDP in eu countries")+scale_fill_gradient(low = "dark blue",high = "red",breaks=c(1e+12,2e+12,3e+12),labels=c("1 Trillion","2 Trillion","3 Trillion"))
gmap
png("GDP map.png",width = 600,height = 600)
gmap
dev.off()
